In [ ]:
import warnings
warnings.filterwarnings('ignore')

# Word Embeddings
## Word2Vec

In [ ]:
# First, you'll need to install gensim
# !pip install gensim

# Import the necessary modules

from gensim.test.utils import common_texts

from gensim.models import Word2Vec

In [ ]:
print(common_texts) #Sample Data

[['human', 'interface', 'computer'], ['survey', 'user', 'computer', 'system', 'response', 'time'], ['eps', 'user', 'interface', 'system'], ['system', 'human', 'system', 'eps'], ['user', 'response', 'time'], ['trees'], ['graph', 'trees'], ['graph', 'minors', 'trees'], ['graph', 'minors', 'survey']]


 Word2vec accepts several parameters that affect both training speed and quality.

One of them is for pruning the internal dictionary. Words that appear only once or twice in a billion-word corpus are probably uninteresting typos and garbage. In addition, there’s not enough data to make any meaningful training on those words, so it’s best to ignore them:

`model = Word2Vec(sentences, min_count=10)  # default value is 5`

A reasonable value for min_count is between 0-100, depending on the size of your dataset.

Another parameter is the size of the NN layers, which correspond to the “degrees” of freedom the training algorithm has:

`model = Word2Vec(sentences, vector_size=200)  # default value is 100`

Bigger size values require more training data, but can lead to better (more accurate) models. Reasonable values are in the tens to hundreds.

Other hyper-parameters:

*   size: window=window_size for capturing context for target word

*   sample: The threshold for configuring which higher-frequency words are randomly down sampled, useful range is (0, 1e-5)

*   workers: Use these many worker threads to train the model (faster training with multicore machines)

*   sg: Training algorithm: skip-gram if sg=1, otherwise CBOW.

*   iter: Number of iterations (epochs) over the corpus.


In [ ]:
model = Word2Vec(sentences=common_texts, vector_size=10, window=5, min_count=1, workers=4)
#Here, vector_size = 10 denotes the length of embedding
model.save("word2vec.model")

If you save the model you can continue training it later:

In [ ]:
# load the saved model
model = Word2Vec.load("word2vec.model")

The trained word vectors are stored in a KeyedVectors instance, as model.wv:

In [ ]:
# Get the embeddings for the word 'human'
embedding = model.wv['human']

print(embedding)
print(len(embedding))

[-0.00410223 -0.08368949 -0.05600012  0.07104538  0.0335254   0.0722567
  0.06800248  0.07530741 -0.03789154 -0.00561806]
10


In [ ]:
# Get the most similar words (having the most similar embeddings)
similar_words = model.wv.most_similar('human',topn = 3) #topn denotes the top 3 similar words
print(similar_words)

[('graph', 0.3586882948875427), ('system', 0.22743132710456848), ('time', 0.1153423935174942)]


In [ ]:
# Store just the words + their trained embeddings.
word_vectors = model.wv
word_vectors.save("word2vec.wordvectors")

In [ ]:
# Load back with memory-mapping = read-only, shared across processes.
from gensim.models import KeyedVectors
wv = KeyedVectors.load("word2vec.wordvectors", mmap='r')
wv['computer']  # Get numpy vector embedding for 'computer'

array([ 0.0163195 ,  0.00189972,  0.03474648,  0.00217841,  0.09621626,
        0.05062076, -0.08919986, -0.0704361 ,  0.00901718,  0.06394394],
      dtype=float32)

### Refer to the link below for more details:
https://radimrehurek.com/gensim/models/word2vec.html

# Gensim comes with several already pre-trained models, in the Gensim-data repository

In [ ]:
import gensim.downloader
# Show all available models in gensim-data
print(list(gensim.downloader.info()['models'].keys()))

['fasttext-wiki-news-subwords-300', 'conceptnet-numberbatch-17-06-300', 'word2vec-ruscorpora-300', 'word2vec-google-news-300', 'glove-wiki-gigaword-50', 'glove-wiki-gigaword-100', 'glove-wiki-gigaword-200', 'glove-wiki-gigaword-300', 'glove-twitter-25', 'glove-twitter-50', 'glove-twitter-100', 'glove-twitter-200', '__testing_word2vec-matrix-synopsis']


In [ ]:
# Download the "glove-twitter-25" embeddings
# Pre-trained glove vectors based on 2B tweets, 27B tokens, 1.2M vocab, uncased.
glove_vectors = gensim.downloader.load('glove-twitter-25')
glove_vectors

[==================================================] 100.0% 104.8/104.8MB downloaded


In [ ]:
# Use the downloaded vectors as usual:
glove_vectors.most_similar('twitter')

[('facebook', 0.948005199432373),
 ('tweet', 0.9403423070907593),
 ('fb', 0.9342358708381653),
 ('instagram', 0.9104824066162109),
 ('chat', 0.8964964747428894),
 ('hashtag', 0.8885937333106995),
 ('tweets', 0.8878158330917358),
 ('tl', 0.8778461217880249),
 ('link', 0.8778210878372192),
 ('internet', 0.8753897547721863)]

In [ ]:
glove_vectors['queen']

array([-1.1266  , -0.52064 ,  0.45565 ,  0.21079 , -0.05081 , -0.65158 ,
        1.1395  ,  0.69897 , -0.20612 , -0.71803 , -0.02811 ,  0.10977 ,
       -3.3089  , -0.49299 , -0.51375 ,  0.10363 , -0.11764 , -0.084972,
        0.02558 ,  0.6859  , -0.29196 ,  0.4594  , -0.39955 , -0.40371 ,
        0.31828 ], dtype=float32)

# Document/Sentence Embeddings
Paragraph, Sentence, and Document embeddings

## Doc2vec

In [ ]:
from gensim.models.doc2vec import Doc2Vec, TaggedDocument

# Define your sentences (example)
sentences = ["this is the first sentence", "this is the second sentence", "yet another sentence", "one more sentence", "and the final sentence"]

# Tag the sentences for training
tagged_data = [TaggedDocument(words=sentence.split(), tags=[str(i)]) for i, sentence in enumerate(sentences)]

# Train the model
model = Doc2Vec(tagged_data, vector_size=10, window=2, min_count=1, workers=4)

# Get the embeddings for the sentences
sentence_vectors = [model.infer_vector(sentence.split()) for sentence in sentences]
# The infer_vectors expects the input as a list of words (nltk.word_tokenize())

print("Sentence Embeddings:")
print(sentence_vectors) #Embeddings of the sentences

import numpy as np
print("\nShape:")
print(np.array(sentence_vectors).shape)

Sentence Embeddings:
[array([ 0.01821357,  0.02594667,  0.04038974,  0.03291611, -0.02587991,
       -0.00589329,  0.00655008, -0.04827507,  0.04916208,  0.00108263],
      dtype=float32), array([ 4.4840805e-02, -2.6123403e-02, -6.1434133e-05,  5.7107997e-03,
       -4.8215697e-03,  4.9016461e-02, -2.1489849e-02, -2.5502274e-02,
       -4.1926078e-02, -4.2932746e-03], dtype=float32), array([ 0.00927534, -0.00318728, -0.02852724, -0.02131686, -0.0186496 ,
        0.02670106, -0.03630985, -0.00882227,  0.03916181,  0.00347719],
      dtype=float32), array([-0.04103417, -0.03968335, -0.01021319, -0.01521414,  0.01974463,
       -0.00486366, -0.01671924,  0.00102357, -0.0154149 ,  0.01048233],
      dtype=float32), array([-0.00556436,  0.01828448, -0.0213437 ,  0.02301039, -0.01649704,
        0.01762558, -0.04732837,  0.01559526, -0.03176651, -0.01864625],
      dtype=float32)]

Shape:
(5, 10)


In [ ]:
sentence_vectors[0] #the first embedding

array([ 0.01821357,  0.02594667,  0.04038974,  0.03291611, -0.02587991,
       -0.00589329,  0.00655008, -0.04827507,  0.04916208,  0.00108263],
      dtype=float32)

In [ ]:
from sklearn.metrics.pairwise import cosine_similarity
cosine_similarity(sentence_vectors[1].reshape(1,-1),sentence_vectors[2].reshape(1,-1))[0][0]
#Cosine similarity between embeddings

0.17146514

In [ ]:
# Find the similarity between all the sentences
similarity = cosine_similarity(sentence_vectors)
similarity

array([[ 0.9999998 , -0.09469897,  0.09594274, -0.6239071 , -0.28149876],
       [-0.09469897,  1.        ,  0.17146516, -0.04729198,  0.34938085],
       [ 0.09594274,  0.17146516,  1.        , -0.02119621,  0.19021074],
       [-0.6239071 , -0.04729198, -0.02119621,  1.0000001 ,  0.01172717],
       [-0.28149876,  0.34938085,  0.19021074,  0.01172717,  0.99999994]],
      dtype=float32)

In [ ]:
#Find the most similar sentence to the first sentence (at index = 0)
ind = 0  # The index of the sentence for which you want to find the most similar sentence
max = -1 # This will store the cosine_similarity of the most similar document
print("Input Sentence -->", sentences[ind])
for i in range(np.array(sentence_vectors).shape[0]):
    if i != ind:
        if max < cosine_similarity(sentence_vectors[i].reshape(1,-1),sentence_vectors[ind].reshape(1,-1))[0][0]:
            max = cosine_similarity(sentence_vectors[i].reshape(1,-1),sentence_vectors[ind].reshape(1,-1))[0][0]
            s_ind = i

print("Most Similar Sentence -->", sentences[s_ind])
print("Cosine Simialrity:", max)

Input Sentence --> this is the first sentence
Most Similar Sentence --> yet another sentence
Cosine Simialrity: 0.09594278


#### More about Doc2vec here:
https://radimrehurek.com/gensim/models/doc2vec.html